micronaut:
  server:
    port: 8080
  application:
    name: NumbersManager
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger
redis:
  number-key: number
  uri: redis://numbers-db:6379/1?timeout=5s
random:
  integer:
    min: -100000
    max: 100000